---
#title: "Divvy Bike Consumer Data"
#author: "Liam Snow"
---
#Setting up the packages
install.packages("dplyr",repos = "http://cran.us.r-project.org",dependencies = TRUE)
library(dplyr)
install.packages("ggplot2",repos = "http://cran.us.r-project.org",dependencies = TRUE)
library(ggplot2)

#reading the data  
Quarter1 = read.csv('C:/Users/Lime/Documents/CKME Capstone/Divvy_Trips_2018_Q1.csv',header = T,sep=',')
Quarter1$quarter=as.factor("Q1")
Quarter2 = read.csv('C:/Users/Lime/Documents/CKME Capstone/Divvy_Trips_2018_Q2.csv',header = T,sep=',')
Quarter2$quarter=as.factor("Q2")
Quarter3 = read.csv('C:/Users/Lime/Documents/CKME Capstone/Divvy_Trips_2018_Q3.csv',header = T,sep=',')
Quarter3$quarter=as.factor("Q3")
Quarter4 = read.csv('C:/Users/Lime/Documents/CKME Capstone/Divvy_Trips_2018_Q4.csv',header = T,sep=',')
Quarter4$quarter=as.factor("Q4")

#Merging Quarters and attach
Divvy2018 =rbind(Quarter1,Quarter2,Quarter3,Quarter4)

#Summary Statistics
dim(Divvy2018)
head(Divvy2018)
lapply(Divvy2018,class)

#Change Tripduration to numeric value
Divvy2018$tripduration=as.numeric(as.character(gsub(",","",Divvy2018$tripduration)))

#Seperate start_time into Date and Time attributes
Divvy2018$start_date=as.Date(Divvy2018$start_time)
Divvy2018$start_time=as.numeric(format(as.POSIXct(Divvy2018$start_time,format='%Y-%m-%d %H:%M:%S'),'%H'))

#Creating Day of the Week and Month
Divvy2018$dayofweek=as.factor(weekdays(Divvy2018$start_date,TRUE))
Divvy2018$month=as.factor(format(Divvy2018$start_date,"%m"))

#Creating typeofday
Divvy2018$typeofday=ifelse(Divvy2018$dayofweek %in% c("Sat","Sun"),"weekend","weekday")

summary(Divvy2018)

#Replacing NAs in gender with proportional equivalent of "Male" and "Female"
set.seed(37)
levels(Divvy2018$gender)[1]=sample(c("Male","Female"),replace=TRUE,prob = c(2281841/(758736+2281841),758736/(2281841+758736)))

#Removing rows with NAs in Birthyear
Divvy2018=na.omit(Divvy2018)

#Removing Tripduration for over an hour
table(Divvy2018$tripduration>3600)
Divvy2018=Divvy2018[!(Divvy2018$tripduration>3600),]

#Changing birthyear to age, removing ages over 90
CurrentAge = function(x) {
Age=(2018-x)
return(Age)
}
Divvy2018$birthyear=sapply(Divvy2018$birthyear,CurrentAge)
colnames(Divvy2018)[colnames(Divvy2018)=="birthyear"]="age"
Divvy2018=Divvy2018[!(Divvy2018$age>80),]

#Removing Non-Consumer Stations
Divvy2018=Divvy2018[!(Divvy2018$from_station_name=="BBB ~ Divvy Parts Testing"),]
Divvy2018=Divvy2018[!(Divvy2018$from_station_name=="TS ~ DIVVY PARTS TESTING"),]
Divvy2018=Divvy2018[(Divvy2018$from_station_name %in% Divvy2018$to_station_name),]
Divvy2018$from_station_name=factor(Divvy2018$from_station_name)
Divvy2018=Divvy2018[!(Divvy2018$to_station_name=="BBB ~ Divvy Parts Testing"),]
Divvy2018=Divvy2018[!(Divvy2018$to_station_name=="TS ~ DIVVY PARTS TESTING"),]
Divvy2018=Divvy2018[(Divvy2018$to_station_name %in% Divvy2018$from_station_name),]
Divvy2018$to_station_name=factor(Divvy2018$to_station_name)

#Removing Unnecessary Attributes
Divvy2018=within(Divvy2018,rm(from_station_id,to_station_id,bikeid,end_time))

#Visualizing Data
ggplot(data=Divvy2018, aes(Divvy2018$tripduration))+geom_histogram(binwidth=150,fill="#B3DDF2")+scale_x_continuous(name = "Trip Duration (s)")+scale_y_continuous(name="Frequency",labels=scales::comma,limits=c(0,600000))+ggtitle("Frequency of Trip Duration")+theme(panel.background = element_rect(fill = 'grey44'))

ggplot(data=Divvy2018, aes(Divvy2018$age))+geom_histogram(binwidth=2,fill="#B3DDF2")+scale_x_continuous(name = "Age")+scale_y_continuous(name="Frequency")+ggtitle("Age of Users")+theme(panel.background = element_rect(fill = 'grey44'))

ggplot(Divvy2018,aes(Divvy2018$gender))+geom_bar(fill="#B3DDF2")+scale_x_discrete(name="Gender")+scale_y_continuous(name="Trips in 2018",labels=scales::comma)+theme(panel.background = element_rect(fill = 'grey44'))+ggtitle("Trips by Gender in 2018")

ggplot(Divvy2018,aes(Divvy2018$usertype))+geom_bar(fill="#B3DDF2")+scale_x_discrete(name="User Type")+scale_y_continuous(name="Trips in 2018",labels=scales::comma)+theme(panel.background = element_rect(fill = 'grey44'))+ggtitle("Trips by Usertype in 2018")

ggplot(Divvy2018,aes(x=Divvy2018$typeofday,y=Divvy2018$tripduration))+geom_boxplot()+ggtitle("Trip Duration on Weekdays and Weeknds")+xlab("")+ylab("Trip Duration")+scale_y_continuous(limits=c(0,3600))+stat_summary(fun.y = mean, geom="text",colour="darkblue", vjust=0.7,aes( label=round(..y.., digits=1)))

ggplot(Divvy2018,aes(Divvy2018$dayofweek))+geom_bar(aes(y = (..count..)/sum(..count..)),fill="#B3DDF2")+scale_x_discrete(name="Day of the Week",limits=c("Sun","Mon","Tue","Wed","Thu","Fri","Sat"))+scale_y_continuous(name="Percentage of Trips per Day",labels=scales::percent)+theme(panel.background = element_rect(fill = 'grey44'))+ggtitle("Trip Perentage per Weekday")

ggplot(Divvy2018,aes(Divvy2018$month))+geom_bar(aes(y = (..count..)/sum(..count..)),fill="#B3DDF2")+scale_x_discrete(name="Month",labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"))+scale_y_continuous(name="Percentage of Trips per Day",labels=scales::percent)+theme(panel.background = element_rect(fill = 'grey44'))+ggtitle("Trip Perentage per Month")

Top10Start=as.data.frame(head(sort(table(Divvy2018$from_station_name),decreasing=TRUE),n=10))
ggplot(Divvy2018,aes(Divvy2018$from_station_name))+geom_bar(fill="#B3DDF2")+scale_x_discrete(name="Starting Station",limits=Top10Start$Var1)+scale_y_discrete(name="Trips over 2018",limits = c(25000,60100))+theme(panel.background = element_rect(fill = 'grey44'))+ggtitle("Top 10 Most Popular Starting Stations")+ theme(axis.text.x = element_text(angle = 90))

Top10To=as.data.frame(head(sort(table(Divvy2018$to_station_name),decreasing=TRUE),n=10))
ggplot(Divvy2018,aes(Divvy2018$to_station_name))+geom_bar(fill="#B3DDF2")+scale_x_discrete(name="Ending Station",limits=Top10To$Var1)+scale_y_discrete(name="Trips over 2018",limits = c(25000,60100))+theme(panel.background = element_rect(fill = 'grey44'))+ggtitle("Top 10 Most Popular Ending Stations")+ theme(axis.text.x = element_text(angle = 90))

#Create Data.Fram with Data to be used
DivvyR=Divvy2018[,c(2,3,8)]

#Checking Correlation for Numeric Data
cor(Divvy2018$tripduration,Divvy2018$start_time)
cor(Divvy2018$tripduration,Divvy2018$age)
#neither is strongly indicating any influence over tripduration

#Creating Dummies to Determine Correlated Variables
install.packages("fastDummies")
library(fastDummies)
#DUmmy for Gender
dummygender=dummy_cols(Divvy2018$gender)
DivvyR$GenderDummy=dummygender[,3]
cor(DivvyR$tripduration,DivvyR$GenderDummy)
#Dummy for Usertype
dummyuser=dummy_cols(Divvy2018$usertype)
DivvyR$userdummy=dummyuser[,3]
cor(DivvyR$tripduration,DivvyR$userdummy)
#Dummy for Type of Day
dummydaytype=dummy_cols(Divvy2018$typeofday)
DivvyR$daytypedummy=dummydaytype[,3]
cor(DivvyR$tripduration,DivvyR$daytypedummy)
#Dummy for Day of the Week
dummymonth=dummy_cols(Divvy2018$dayofweek)
DivvyR$tuesdaydummy=dummymonth[,3]
cor(DivvyR$tripduration,DivvyR$tuesdaydummy)
DivvyR$wednesdaydummy=dummymonth[,4]
cor(DivvyR$tripduration,DivvyR$wednesdaydummy)
DivvyR$thursdaydummy=dummymonth[,5]
cor(DivvyR$tripduration,DivvyR$thursdaydummy)
DivvyR$fridaydummy=dummymonth[,6]
cor(DivvyR$tripduration,DivvyR$fridaydummy)
DivvyR$saturdaydummy=dummymonth[,7]
cor(DivvyR$tripduration,DivvyR$saturdaydummy)
DivvyR$sundaydummy=dummymonth[,8]
cor(DivvyR$tripduration,DivvyR$sundaydummy)
#Dummy for month
dummymonth=dummy_cols(Divvy2018$month)
DivvyR$febdummy=dummymonth[,3]
cor(DivvyR$tripduration,DivvyR$jandummy)
DivvyR$mardummy=dummymonth[,4]
cor(DivvyR$tripduration,DivvyR$febdummy)
DivvyR$aprdummy=dummymonth[,5]
cor(DivvyR$tripduration,DivvyR$aprdummy)
DivvyR$maydummy=dummymonth[,6]
cor(DivvyR$tripduration,DivvyR$maydummy)
DivvyR$jundummy=dummymonth[,7]
cor(DivvyR$tripduration,DivvyR$jundummy)
DivvyR$juldummy=dummymonth[,8]
cor(DivvyR$tripduration,DivvyR$juldummy)
DivvyR$augdummy=dummymonth[,9]
cor(DivvyR$tripduration,DivvyR$augdummy)
DivvyR$sepdummy=dummymonth[,10]
cor(DivvyR$tripduration,DivvyR$sepdummy)
DivvyR$octdummy=dummymonth[,11]
cor(DivvyR$tripduration,DivvyR$octdummy)
DivvyR$novdummy=dummymonth[,12]
cor(DivvyR$tripduration,DivvyR$novdummy)
DivvyR$decdummy=dummymonth[,13]
cor(DivvyR$tripduration,DivvyR$decdummy)
#Dummy for Quarter
dummyq=dummy_cols(Divvy2018$quarter)
DivvyR$q2dummy=dummyq[,3]
cor(DivvyR$tripduration,DivvyR$q2dummy)
DivvyR$q3dummy=dummyq[,4]
cor(DivvyR$tripduration,DivvyR$q3dummy)
DivvyR$q4dummy=dummyq[,5]
cor(DivvyR$tripduration,DivvyR$q4dummy)
#The best predictors appear to be usertype, gender and type of day. Though none of the correlations are particularly strong

summary(lm(DivvyR$tripduration~DivvyR$userdummy+DivvyR$GenderDummy+DivvyR$daytypedummy))